### ISSUE TITLE
zipping issue

### ISSUE THREAD

**Issue by Deku2137** [CryllicBuster273/device_xiaomi_phoenix#2]
line 1561, in FindTransfers
AssertionError
18:29:37 ninja failed with: exit status 1
#### failed to build some targets (07:59:40 (hh:mm:ss)) 
any fix for it  ?

**Comment by adi8900** [comment]
Yes, remove your Google cloud instance

**Comment by KakatkarAkshay** [comment]
> Yes, remove your Google cloud instance

Lmao

**Comment by Deku2137** [comment]
any fix for this ?XD

**Comment by KakatkarAkshay** [comment]
> any fix for this ?XD

Yes spam your rom source dev. It's source side issue.
